# Generated by Django 2.2.1 on 2019-05-29 19:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('u_roll', models.PositiveIntegerField(verbose_name='University Roll no.')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('sem', models.PositiveIntegerField(choices=[('6', '6'), ('4', '4'), ('2', '2'), ('7', '7'), ('5', '5'), ('8', '8'), ('3', '3'), ('', 'select'), ('1', '1')], default=5, verbose_name='Semesert')),
                ('gender', models.CharField(choices=[('', 'select'), ('Female', 'Female'), ('Male', 'Male')], default='Male', max_length=50, verbose_name='Gender')),
                ('addess', models.CharField(max_length=50, verbose_name='Address')),
                ('birth_date', models.DateField(default=datetime.date.today, verbose_name='Date of birth')),
                ('ditrict', models.CharField(max_length=50, verbose_name='District')),
                ('pin', models.PositiveIntegerField(verbose_name='Pin')),
                ('contact', models.PositiveIntegerField(verbose_name='Contact')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
