# Generated by Django 2.2.4 on 2019-08-29 18:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedIntern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intern_id', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=10000)),
                ('apply_before', models.DateField(default=datetime.date.today)),
                ('Campus_date', models.DateField(default=datetime.date.today)),
                ('Salary', models.PositiveIntegerField(verbose_name='Salary')),
                ('Venue', models.CharField(max_length=100)),
                ('Joining_location', models.CharField(max_length=100)),
                ('percentage_Aggregate', models.PositiveIntegerField(verbose_name='Aggregate Percentage')),
                ('percentage_12', models.PositiveIntegerField(verbose_name='Aggregate Percentage')),
                ('percentage_10', models.PositiveIntegerField(verbose_name='Aggregate Percentage')),
                ('experience', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=500)),
                ('starting_date', models.DateField(default=datetime.date.today)),
                ('ending_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=60, verbose_name='First Name')),
                ('m_name', models.CharField(max_length=60, verbose_name='Middle Name')),
                ('l_name', models.CharField(max_length=60, verbose_name='Last Name')),
                ('full_name', models.CharField(max_length=60, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=50)),
                ('u_roll', models.PositiveIntegerField(verbose_name='University Roll no.')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('sem', models.CharField(choices=[('', 'select'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=1, verbose_name='Semester')),
                ('gender', models.CharField(choices=[('', 'select'), ('Female', 'Female'), ('Male', 'Male')], default='Male', max_length=50, verbose_name='Gender')),
                ('addess', models.CharField(max_length=50, verbose_name='Address')),
                ('birth_date', models.DateField(default=datetime.date.today, verbose_name='Date of birth')),
                ('ditrict', models.CharField(max_length=50, verbose_name='District')),
                ('pin', models.PositiveIntegerField(verbose_name='Pin')),
                ('contact', models.PositiveIntegerField(verbose_name='Contact')),
                ('PREFRENCE_first', models.CharField(choices=[('', 'select'), ('Placement', 'Placement'), ('CAT', 'CAT'), ('GATE', 'GATE'), ('OTHER', 'OTHER')], max_length=20, verbose_name='First prefrence')),
                ('PREFRENCE_sec', models.CharField(choices=[('', 'select'), ('Placement', 'Placement'), ('CAT', 'CAT'), ('GATE', 'GATE'), ('OTHER', 'OTHER')], max_length=20, verbose_name='Second prefrence')),
                ('PREFRENCE_third', models.CharField(choices=[('', 'select'), ('Placement', 'Placement'), ('CAT', 'CAT'), ('GATE', 'GATE'), ('OTHER', 'OTHER')], max_length=20, verbose_name='Third prefrence')),
                ('Marks_10', models.CharField(max_length=50, verbose_name='10th Percentage')),
                ('passing_year_10', models.IntegerField(verbose_name='10th Passing Year YYYY')),
                ('Marks_12', models.CharField(max_length=50, verbose_name='12th Percentage')),
                ('passing_year_12', models.PositiveIntegerField(verbose_name='12th passing year YYYY')),
                ('Marks_Diploma', models.CharField(max_length=50, verbose_name='Diploma Percentage')),
                ('addmission_year_Diploma', models.PositiveIntegerField(verbose_name='Admisson year BE')),
                ('backlog', models.PositiveIntegerField(verbose_name='No. of active backlog')),
                ('sem_1_per', models.PositiveIntegerField(verbose_name='1st Semester percentage')),
                ('sem_2_per', models.PositiveIntegerField(verbose_name='2nd Semester percentage')),
                ('sem_3_per', models.PositiveIntegerField(verbose_name='3rd Semester percentage')),
                ('sem_4_per', models.PositiveIntegerField(verbose_name='4th Semester percentage')),
                ('sem_5_per', models.PositiveIntegerField(verbose_name='5th Semester percentage')),
                ('sem_6_per', models.PositiveIntegerField(verbose_name='6th Semester percentage')),
                ('sem_7_per', models.PositiveIntegerField(verbose_name='7th Semester percentage')),
                ('father_name', models.CharField(max_length=60, verbose_name='Father Name')),
                ('father_contact', models.PositiveIntegerField(verbose_name='Father Contact')),
                ('mother_name', models.CharField(max_length=60, verbose_name='Mother Name')),
                ('mother_contact', models.PositiveIntegerField(verbose_name='Mother Contact')),
                ('emergency_contact', models.PositiveIntegerField(verbose_name='Emergency Contact')),
                ('course', models.CharField(choices=[('', 'select'), ('Female', 'Female'), ('Male', 'Male')], default='Male', max_length=50, verbose_name='Course')),
                ('Enrollment_no', models.CharField(max_length=50, verbose_name='Enrollment no')),
                ('Dept', models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('EEE', 'EEE'), ('EE', 'EE'), ('CIVIL', 'CIVIL'), ('MECH', 'MECH'), ('ETC', 'ETC')], max_length=50, verbose_name='Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
