# Generated by Django 2.2.4 on 2019-08-29 18:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedintern',
            name='intern_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='appliedintern',
            name='user_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='Campus_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='Joining_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='Salary',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='Venue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='apply_before',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='body',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='head',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='percentage_10',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Aggregate Percentage'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='percentage_12',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Aggregate Percentage'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='percentage_Aggregate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Aggregate Percentage'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='body',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='ending_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='head',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='starting_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Dept',
            field=models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('EEE', 'EEE'), ('EE', 'EE'), ('CIVIL', 'CIVIL'), ('MECH', 'MECH'), ('ETC', 'ETC')], max_length=50, null=True, verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Enrollment_no',
            field=models.CharField(max_length=50, null=True, verbose_name='Enrollment no'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Marks_10',
            field=models.CharField(max_length=50, null=True, verbose_name='10th Percentage'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Marks_12',
            field=models.CharField(max_length=50, null=True, verbose_name='12th Percentage'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Marks_Diploma',
            field=models.CharField(max_length=50, null=True, verbose_name='Diploma Percentage'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='PREFRENCE_first',
            field=models.CharField(choices=[('', 'select'), ('Placement', 'Placement'), ('CAT', 'CAT'), ('GATE', 'GATE'), ('OTHER', 'OTHER')], max_length=20, null=True, verbose_name='First prefrence'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='PREFRENCE_sec',
            field=models.CharField(choices=[('', 'select'), ('Placement', 'Placement'), ('CAT', 'CAT'), ('GATE', 'GATE'), ('OTHER', 'OTHER')], max_length=20, null=True, verbose_name='Second prefrence'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='PREFRENCE_third',
            field=models.CharField(choices=[('', 'select'), ('Placement', 'Placement'), ('CAT', 'CAT'), ('GATE', 'GATE'), ('OTHER', 'OTHER')], max_length=20, null=True, verbose_name='Third prefrence'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='addess',
            field=models.CharField(max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='addmission_year_Diploma',
            field=models.PositiveIntegerField(null=True, verbose_name='Admisson year BE'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='backlog',
            field=models.PositiveIntegerField(null=True, verbose_name='No. of active backlog'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.PositiveIntegerField(null=True, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(choices=[('', 'select'), ('Female', 'Female'), ('Male', 'Male')], default='Male', max_length=50, null=True, verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ditrict',
            field=models.CharField(max_length=50, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emergency_contact',
            field=models.PositiveIntegerField(null=True, verbose_name='Emergency Contact'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='f_name',
            field=models.CharField(max_length=60, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='father_contact',
            field=models.PositiveIntegerField(null=True, verbose_name='Father Contact'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='father_name',
            field=models.CharField(max_length=60, null=True, verbose_name='Father Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=60, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('', 'select'), ('Female', 'Female'), ('Male', 'Male')], default='Male', max_length=50, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='l_name',
            field=models.CharField(max_length=60, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='m_name',
            field=models.CharField(max_length=60, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mother_contact',
            field=models.PositiveIntegerField(null=True, verbose_name='Mother Contact'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mother_name',
            field=models.CharField(max_length=60, null=True, verbose_name='Mother Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passing_year_10',
            field=models.IntegerField(null=True, verbose_name='10th Passing Year YYYY'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passing_year_12',
            field=models.PositiveIntegerField(null=True, verbose_name='12th passing year YYYY'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.PositiveIntegerField(null=True, verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sem',
            field=models.CharField(choices=[('', 'select'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=1, null=True, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sem_1_per',
            field=models.PositiveIntegerField(null=True, verbose_name='1st Semester percentage'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sem_2_per',
            field=models.PositiveIntegerField(null=True, verbose_name='2nd Semester percentage'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sem_3_per',
            field=models.PositiveIntegerField(null=True, verbose_name='3rd Semester percentage'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sem_4_per',
            field=models.PositiveIntegerField(null=True, verbose_name='4th Semester percentage'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sem_5_per',
            field=models.PositiveIntegerField(null=True, verbose_name='5th Semester percentage'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sem_6_per',
            field=models.PositiveIntegerField(null=True, verbose_name='6th Semester percentage'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sem_7_per',
            field=models.PositiveIntegerField(null=True, verbose_name='7th Semester percentage'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='u_roll',
            field=models.PositiveIntegerField(null=True, verbose_name='University Roll no.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
