# Generated by Django 2.2.1 on 2019-06-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190601_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sem',
            field=models.PositiveIntegerField(choices=[('3', '3'), ('4', '4'), ('2', '2'), ('5', '5'), ('6', '6'), ('7', '7'), ('', 'select'), ('8', '8'), ('1', '1')], default=5, verbose_name='Semesert'),
        ),
    ]
