# Generated by Django 2.2.4 on 2019-09-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190918_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='Description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='Description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
