# Generated by Django 2.2.4 on 2019-08-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20190830_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Marks_10',
            field=models.PositiveIntegerField(null=True, verbose_name='10th Percentage'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Marks_12',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='12th Percentage'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Marks_Diploma',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Diploma Percentage'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sem',
            field=models.PositiveIntegerField(choices=[('', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8)], null=True, verbose_name='Semester'),
        ),
    ]
