# Generated by Django 2.2.4 on 2019-09-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20190918_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='Description',
            field=models.TextField(max_length=100000, null=True),
        ),
    ]
