# Generated by Django 2.2.4 on 2019-09-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20190918_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='Description',
            field=models.TextField(max_length=100000, null=True),
        ),
    ]
