# Generated by Django 2.2.1 on 2019-06-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20190601_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sem',
            field=models.PositiveIntegerField(choices=[('1', '1'), ('2', '2'), ('4', '4'), ('3', '3'), ('5', '5'), ('7', '7'), ('8', '8'), ('6', '6'), ('', 'select')], default=5, verbose_name='Semesert'),
        ),
    ]
