# Generated by Django 2.2.1 on 2019-06-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20190601_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sem',
            field=models.PositiveIntegerField(choices=[('5', '5'), ('2', '2'), ('3', '3'), ('6', '6'), ('8', '8'), ('4', '4'), ('', 'select'), ('7', '7'), ('1', '1')], default=5, verbose_name='Semesert'),
        ),
    ]
