# Generated by Django 2.2.1 on 2019-06-01 07:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20190601_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='addess',
            field=models.CharField(max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.PositiveIntegerField(null=True, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ditrict',
            field=models.CharField(max_length=50, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('', 'select'), ('Female', 'Female'), ('Male', 'Male')], default='Male', max_length=50, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=60, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.PositiveIntegerField(null=True, verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sem',
            field=models.PositiveIntegerField(choices=[('1', '1'), ('2', '2'), ('5', '5'), ('7', '7'), ('8', '8'), ('6', '6'), ('', 'select'), ('4', '4'), ('3', '3')], default=5, null=True, verbose_name='Semesert'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='u_roll',
            field=models.PositiveIntegerField(null=True, verbose_name='University Roll no.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
