# Generated by Django 2.2.1 on 2019-06-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20190601_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sem',
            field=models.PositiveIntegerField(choices=[('2', '2'), ('3', '3'), ('1', '1'), ('5', '5'), ('4', '4'), ('6', '6'), ('8', '8'), ('', 'select'), ('7', '7')], default=5, null=True, verbose_name='Semesert'),
        ),
    ]
