# Generated by Django 2.2.1 on 2019-06-01 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20190601_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100, null=True)),
                ('body', models.CharField(max_length=500, null=True)),
                ('starting_date', models.DateField(default=datetime.date.today, null=True)),
                ('ending_date', models.DateField(default=datetime.date.today, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='sem',
            field=models.PositiveIntegerField(choices=[(1, '1'), (5, '5'), (4, '4'), (7, '7'), (2, '2'), ('', 'select'), (8, '8'), (3, '3'), (6, '6')], null=True, verbose_name='Semesert'),
        ),
    ]
