# Generated by Django 2.2.1 on 2019-06-02 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20190601_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100, null=True)),
                ('body', models.CharField(max_length=500, null=True)),
                ('starting_date', models.DateField(default=datetime.date.today, null=True)),
                ('ending_date', models.DateField(default=datetime.date.today, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='sem',
            field=models.PositiveIntegerField(choices=[(6, '6'), (3, '3'), (8, '8'), ('', 'select'), (2, '2'), (4, '4'), (5, '5'), (7, '7'), (1, '1')], null=True, verbose_name='Semester'),
        ),
    ]
