# Generated by Django 2.2.1 on 2019-06-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20190602_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sem',
            field=models.CharField(choices=[('8', '8'), ('2', '2'), ('5', '5'), ('6', '6'), ('7', '7'), ('', 'select'), ('3', '3'), ('4', '4'), ('1', '1')], max_length=1, null=True, verbose_name='Semester'),
        ),
    ]
