# Generated by Django 2.2.1 on 2019-06-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20190604_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='body',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sem',
            field=models.CharField(choices=[('6', '6'), ('7', '7'), ('8', '8'), ('3', '3'), ('4', '4'), ('', 'select'), ('5', '5'), ('1', '1'), ('2', '2')], max_length=1, null=True, verbose_name='Semester'),
        ),
    ]
