# Generated by Django 2.2.1 on 2019-06-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20190606_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedIntern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intern_id', models.PositiveIntegerField(null=True)),
                ('user_id', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='sem',
            field=models.CharField(choices=[('5', '5'), ('2', '2'), ('3', '3'), ('1', '1'), ('7', '7'), ('8', '8'), ('6', '6'), ('4', '4'), ('', 'select')], max_length=1, null=True, verbose_name='Semester'),
        ),
    ]
